### ISSUE TITLE
TypeError: listener must be a function

### ISSUE THREAD

**Issue by justinmchase** [AveVlad/gulp-connect#148]
This may be a windows issue, I'm not sure but trying to run it for the first time on windows (the same code is working on a mac) we get this error:

```
[12:16:33] 'connect' errored after 1.69 s
[12:16:33] TypeError: listener must be a function
   at Server.addListener (events.js:197:11)
   at new Server (https.js:29:10)
   at Object.exports.createServer (https.js:44:10)
   at ConnectApp.server (c:\example\node_modules\gulp-connect\index.js:47:22)
   at new ConnectApp (c:\example\node_modules\gulp-connect\index.js:37:10)
   at Object.module.exports.server (c:\example\node_modules\gulp-connect\index.js:170:12)
```

The error appears to saying that the call to `https.createServer` is not receiving a function as the second argument. What could be causing this?

**Comment by justinmchase** [comment]
@krswanson

**Comment by 632781460** [comment]
yeah,i have the problem too,because the connect depency version  is < 2.18,and there is connect that is version 1.9.2 in node_modules, so  npm 3.5 will use 1.9.2 for gulp-connect.
please fix it , thx.

**Comment by 632781460** [comment]
it is incompatible between connect 1.92 with gulp-connect 2.2

**Comment by justinmchase** [comment]
Is there a workaround @632781460 ?

**Comment by 632781460** [comment]
my fork works for me ,you can try it

**Comment by 632781460** [comment]
@justinmchase

**Comment by justinmchase** [comment]
@632781460 Can you submit that as a pull request?

**Comment by justinmchase** [comment]
This was fixed.
