### ISSUE TITLE
have some problem use gzip

### ISSUE THREAD

**Issue by twang281314** [AveVlad/gulp-connect#193]
I want to use gzip ,here is the code
```
  connect.server({
     root: 'dist',
     livereload: false,
     port: 8080,
     middleware: function(connect, opt) {
         return [modRewrite([
             '^/api/(.*)$ http://localhost:8081/$1 [P]',
             '^/ims_api/(.*)$ http://192.168.6.143:8080/$1 [P]',
             '^/oms_api/(.*)$ http://192.168.6.133:8080/$1 [P]',
             '^/wos_api/(.*)$ http://192.168.6.144:8080/$1 [P]'
         ]), historyApiFallback(), require('connect-gzip').gzip()];

     }
 });
```
but when I start the server ,

```
Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at Socket._writeGeneric (net.js:705:26)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:650:40)
    at ServerResponse.res.write (F:\iscs\web\node_modules\.npminstall\connect-gzip\0.1.6\connect-gzip\lib\gzip.js:82:20)
    at ServerResponse.res.(anonymous function) (F:\iscs\web\node_modules\.npminstall\connect-gzip\0.1.6\connect-gzip\lib\gzip.js:46:19)
    at ReadStream.ondata (_stream_readable.js:561:20)
```
I do not know why, please give me some advise, thanks

**Comment by davityavryan** [comment]
hey @twang281314 did you find any solution here?
help?

**Comment by twang281314** [comment]
https://github.com/expressjs/compression

**Comment by twang281314** [comment]
@davityavryan https://github.com/expressjs/compression

**Comment by davityavryan** [comment]
Thanks. @twang281314
