### ISSUE TITLE
Seeing this error

### ISSUE THREAD

**Issue by shgattu** [AveVlad/gulp-connect#224]
Hi,
I am seeing below error when I run gulp connect. 
Any help will be really appreciated.

Thanks,
Shwetha
10:38:25] Starting 'connect'...
[10:38:25] 'connect' errored after 6.57 ms
[10:38:25] TypeError: connect.static is not a function
    at /rmbs/apps/node_modules/gulp-connect/index.js:158:44
    at Array.forEach (native)
    at ConnectApp.handlers (/rmbs/apps/node_modules/gulp-connect/index.js:157:17)
    at ConnectApp.run (/rmbs/apps/node_modules/gulp-connect/index.js:55:10)
    at new ConnectApp (/rmbs/apps/node_modules/gulp-connect/index.js:50:10)
    at Object.module.exports.server (/rmbs/apps/node_modules/gulp-connect/index.js:219:11)

**Comment by shgattu** [comment]
This is the snippet from gulpfile.js

gulp.task('connect', function() {
    connect.server({
        root: ['dist'],
        port: 8000

    });
});

**Comment by leogouveia** [comment]
Hi, I just discovered there was breaking changes on connect version 3.6.6, so, there's no more connect.static(..).
You should use serve-static instead of connect.static().
See the documentation from [connect](https://www.npmjs.com/package/connect#middleware) and [serve-static](https://www.npmjs.com/package/serve-static).
Here is an example of how I solved this problem:
`
const serveStatic = require('serve-static');
...
connect.server({
    name: '...',
    root: ['./src/cliente', './bower_components'],
    port: 3002,
    middleware: connect => 
      [
        connect().use('/bower_components', serveStatic('./bower_components')),
        connect().use('/node_modules', serveStatic('./node_modules'))
      ]
  })
`
