### ISSUE TITLE
"TypeError: http2.createSecureServer is not a function"

### ISSUE THREAD

**Issue by shark-horse** [avevlad/gulp-connect#255]
I'm trying to diagnose an issue with Chrome / Chromium and HTTP2 by doing tests with a Gulp-connect server we use during development.

I added the http2 module:

`yarn add --dev http2` 

and even added a `require('http2')` statement at the beginning of my `gulpfile.js`, but I get:

```
TypeError: http2.createSecureServer is not a function
    at ConnectApp.run (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/gulp-connect/index.js:96:29)
    at new ConnectApp (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/gulp-connect/index.js:57:10)
    at Object.server (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/gulp-connect/index.js:268:11)
    at startServer (/home/jason/Pro2.0/Yawl2/yawl_client/gulpfile.js:237:11)
    at Gulp.<anonymous> (/home/jason/Pro2.0/Yawl2/yawl_client/gulpfile.js:397:3)
    at module.exports (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/orchestrator/index.js:214:10)
    at /home/jason/Pro2.0/Yawl2/yawl_client/node_modules/orchestrator/index.js:279:18
    at finish (/home/jason/Pro2.0/Yawl2/yawl_client/node_modules/orchestrator/lib/runTask.js:21:8)
```

I think the README is referring to a different http2 module, perhaps? What is it called? [http2](https://www.npmjs.com/package/http2) is deprecated and has no `createSecureServer` member, but it does have a `createServerTLS` ([link](https://github.com/molnarg/node-http2/blob/master/lib/http.js#L609)).

**Comment by shark-horse** [comment]
I see now the README has a link to the same module, so I don't think I made a mistake there.

**Comment by AleCaste** [comment]
gulp-connect version 5.0.0 uses the http2 module.
But newer versions (like 5.7.0) use the built-in http2 module from node (you must have node 9 or newer).
The message you are getting is because you are using a new version of gulp-connect (which does NOT use the standalone http2 anymore) but your node version is < than 9

**Comment by shark-horse** [comment]
Sorry I had forgotten all about this thread. IIRC gulp-connect does not work with http2... maybe I can provide more concrete detail another time.
