### ISSUE TITLE
please update docs with examples for gulp 4

### ISSUE THREAD

**Issue by johnybrownalreadytaken** [avevlad/gulp-connect#263]
all in the title

**Comment by huyanhp** [comment]
Yeah, I tried it on gulp 4 and got this error

`[15:04:11] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (C:\www\xxx\front_end\build_script\node_modules\readable-stream\lib\_stream_readable.js:557:8)
    at bound (domain.js:280:14)
    at asyncRunner (C:\www\xxx\front_end\build_script\node_modules\async-done\index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
`

**Comment by filefi** [comment]
An example as follow:
```js
const gulp = require('gulp');
const connect = require('gulp-connect')


function serve(){
    const options={
        port:8080, 
        livereload:true,
    };
    connect.server(options);
}


function html(){
    return gulp.src('./src/html/*.html')
        .pipe(gulp.dest('./dist'))
        .pipe(connect.reload()
}

function css(){
    return gulp.src('./src/css/*.css')
        .pipe(gulp.dest('./dist/css'))
        .pipe(connect.reload())
}


function js(){
    return gulp.src('./src/js/*.js')
        .pipe(gulp.dest('./dist/js'))
        .pipe(connect.reload())
}


function watch(){
    gulp.watch('./src/html/*.html',html);
    gulp.watch('./src/css/*.css',css);
    gulp.watch('./src/js/*.js',js);
}


exports.default = gulp.series(html, css, js, gulp.parallel(watch,serve));
```
