### ISSUE TITLE
Cannot start webserver with proxy support

### ISSUE THREAD

**Issue by ajbogh** [AveVlad/gulp-connect#96]
Here is my configuration:

    gulp.src( './build' )
        .pipe(webserver({
            host:             '0.0.0.0',
            port:             4321,
            livereload:       true,
            directoryListing: false,
            fallback: 'index.html',
            https: true,
            key: 'config/grunt-connect/server.key',
            cert: 'config/grunt-connect/server.crt',
            proxies: [{
                context: '/api',
                target: 'https://otherdomain.com/api'
            },
            {
                context: '/content',
                target: 'https://otherdomain.com/content'
            }]
            //ca: 'config/grunt-connect/ca.crt', //unused option? copied from grunt-connect
        }));

Here is the error:

    [13:09:11] TypeError: Cannot read property 'handle' of undefined
    at Function.app.use (/home/user/Projects/myproject/node_modules/gulp-webserver/node_modules/connect/lib/proto.js:56:30)
    at module.exports (/home/user/Projects/myproject/node_modules/gulp-webserver/src/index.js:148:9)
    at Gulp.<anonymous> (/home/user/Projects/myproject/gulpfile.js:52:15)
    at module.exports (/home/user/Projects/myproject/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/user/Projects/myproject/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/user/Projects/myproject/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/ajbogh/Projects/myproject/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)

Reviewing the function in question from the TypeError shows that it's trying to get the handle of livereload:

    // wrap sub-apps
    console.log(fn, fn.handle);
    if ('function' == typeof fn.handle) {

Here's the output: 

    [13:30:31] Starting 'webserver'...
    [Function: livereload] undefined

Please, if there is some configuration option that I'm missing, please help me understand. This is for a large project that requires some complex proxy support. I would appreciate the help.

**Comment by ajbogh** [comment]
Woops, wrong project! Closing.
